---

- name: "Setup target Report Package"
  shell: |
    sudo rm -rf {{ ieducar__base_path }}/packages/portabilis/i-educar-reports-package
  when:
    - ieducar__install_reports_package_community_edition|bool == true

# - name: Git Checkout the Report Package of i-Educar {{ ieducar__version }}
#   git:
#     repo: "{{ ieducar__url_repository_reports_package_community_edition }}"
#     version: "{{ ieducar__version_reports_package_community_edition }}"
#     dest: "{{ ieducar__base_path }}/packages/portabilis/i-educar-reports-package"
#     clone: yes
#     update: yes
#   when:
#     - ieducar__install_reports_package_community_edition|bool == true

- name: "Install the Report Package of i-Educar {{ ieducar__version }}"
  shell: |
    cd {{ ieducar__base_path }}
    sudo yes | composer update-install
    sudo php artisan community:reports:link
    sudo php artisan reports:install
  when:
    - ieducar__install_reports_package_community_edition|bool == true
  notify: restart ieducar