---

- include_tasks: create_users.yml
- include_tasks: databases.yml
- include_tasks: grant_users.yml

# TODO: Tentar remover passo e reiniciar o serviço via handler 
- name: Setup cluster to default to UTF-8 | Restart PostgreSQL Cluster
  become: yes
  become_user: root
  service:
    name: postgresql
    state: restarted

# - name: Download i-Educar {{ ieducar__version }}
#   get_url:
#     url: https://github.com/portabilis/i-educar/releases/download/{{ ieducar__version }}/ieducar-{{ ieducar__version }}.tar.gz
#     dest: /home/{{ ieducar__run_user }}/ieducar-{{ ieducar__version }}.tar.gz

- name: Git Checkout i-Educar {{ ieducar__version }}
  become: yes
  become_user: root
  git:
    repo: "{{ ieducar__url_repository }}"
    version: "{{ ieducar__version }}"
    dest: "{{ ieducar__base_path }}"
    clone: yes
    update: yes

# - name: "Extract package i-Educar {{ ieducar__version }}"
#   #become: yes
#   #become_user: "{{ ieducar__run_user }}"
#   #become_method: sudo
#   shell: |
#     sudo rm -rf {{ ieducar__base_path }} || true
#     [ -d /var/www ] || sudo mkdir -p /var/www
#     sudo tar -zxf /home/{{ ieducar__run_user }}/ieducar-{{ ieducar__version }}.tar.gz -C /var/www/
#     sudo mv {{ ieducar__base_path }}-{{ ieducar__version }} {{ ieducar__base_path }}

- name: "Install package composer {{ composer__version }}"
  shell: |
    sudo curl -sS https://getcomposer.org/installer -o composer-setup.php
    HASH=`curl -sS https://composer.github.io/installer.sig`
    sudo php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version={{ composer__version }}

- name: "Copy file .env if not exists"
  shell: |
    cd {{ ieducar__base_path }}
    sudo php -r "file_exists('.env') || copy('.env.example', '.env');"

- name: "Fix permission i-Educar"
  become: yes
  become_user: root
  shell: |
    sudo chown -R {{ ieducar__run_user }}:www-data {{ ieducar__base_path }}
    sudo chmod g+s {{ ieducar__base_path }}
    sudo setfacl -R -m g::rwx {{ ieducar__base_path }}
    sudo setfacl -d -m o::rx {{ ieducar__base_path }}

- name: Read values from environment
  shell: "source {{ env_path }}; echo ${{ item|upper }}"
  register: output
  with_items: "{{ values }}"
  args:
    executable: /bin/bash
  changed_when: false

- name: Store read value
  set_fact:
    "{{ item.0 }}": "{{ item.1.stdout }}"
  when: '{{ item.0 }} is undefined'
  with_together:
    - "{{ values }}"
    - "{{ output.results }}"
  changed_when: false

- name: Configure global settings i-Educar
  lineinfile:
    dest: "{{ ieducar__base_path }}/.env"
    backrefs: yes
    regexp: "^{{ item.option }}.+$"
    line: "{{ item.option }}={{ item.value }}"
    state: "{{ item.state | default('present') }}"
    backup: yes
  loop:
    - { option: 'APP_ENV', value: "{{ ieducar_app_env if ieducar_app_env is defined else 'local' }}" }
    - { option: 'APP_DEBUG', value: "{{ ieducar_app_debug if ieducar_app_debug is defined else 'true' }}" }
    - { option: 'DB_HOST', value: "{{ ieducar_db_host if ieducar_db_host is defined else '127.0.0.1' }}" }
    - { option: 'DB_PORT', value: "{{ ieducar_db_port if ieducar_db_port is defined else '5432' }}" }
    - { option: 'DB_DATABASE', value: "{{ ieducar_db_database if ieducar_db_database is defined else DB_DATABASE }}" }
    - { option: 'DB_USERNAME', value: "{{ ieducar_db_username if ieducar_db_username is defined else DB_USERNAME }}" }
    - { option: 'DB_PASSWORD', value: "{{ ieducar_db_password if ieducar_db_password is defined else DB_PASSWORD }}" }

- name: Copy site-available i-Educar to Nginx
  become: yes
  become_user: root
  template:
    src: "{{ ieducar__conf_nginx }}"
    dest: "{{ nginx__config_path }}/sites-available/ieducar"

- name: "Remove site-enabled default of Nginx"
  become: yes
  become_user: root
  shell: |
    sudo rm -rf /etc/nginx/sites-enabled/*

- name: "Enable site-enabled i-Educar of Nginx"
  become: yes
  become_user: root
  shell: |
    sudo ln -sf {{ nginx__config_path }}/sites-available/ieducar {{ nginx__config_path }}/sites-enabled/ieducar

- name: "Install i-Educar {{ ieducar__version }}"
  shell: |
    cd {{ ieducar__base_path }}
    sudo yes | composer new-install
    sudo php artisan storage:link
  notify: restart ieducar