---

- name: Checking total server memory
  vars:
    memory_min_required: "{{ system__memory_min_required | default('2') }}"
    memory_current: "{{ (ansible_memtotal_mb/1000)|round|int }}"
  assert:
    that:
      - "{{ memory_current }} >= {{ memory_min_required }}"
    success_msg: "Memory requirement accepted, current memory {{ memory_current }} GB"
    fail_msg: "Insufficient memory, required memory greater than or equal to {{ memory_min_required }}GB, current memory {{ memory_current }}GB"
  when:
    - system__check_memory_min_required|bool == true
#    - inventory_hostname in groups["dbservers"]