---

# - name: Print all available facts
#   debug:
#     var: ansible_facts

- name: System information
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }} {{ ansible_distribution_version }}"

- include_tasks: checking_requirements_software.yml
- include_tasks: checking_requirements_hardware.yml
- include_tasks: install.yml

- name: Ensure configured time zone is present
  timezone:
    name: "{{ system__time_zone }}"