---

- name: System information
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }} {{ ansible_distribution_version }}"

- include_tasks: checking_requirements_software.yml
- include_tasks: checking_requirements_hardware.yml
- include_tasks: install.yml
- include_tasks: locale.yml

- name: Ensure configured time zone is present
  community.general.timezone:
    name: "{{ system__time_zone }}"